###
## OBTENER TODAS LAS PELICULAS
GET http://127.0.0.1:5000/comentario/
Accept: application/json

###
## AGREGAR UN COMENTARIO
POST http://127.0.0.1:5000/comentario/
Content-Type: application/json

{
    "data": {
        "comentario": "Hola",
        "idUser":1,
        "idMovie":1
    }
}

###
## ACTUALIZAR UN COMENTARIO
PUT http://127.0.0.1:5000/comentario/5
Content-Type: application/json

{
    "data": {
        "comentario": "Hola",
        "idUser":4,
        "idMovie":4
    }
}

###
## ELIMINAR UN COMENTARIO
DELETE http://127.0.0.1:5000/comentario/5
Accept: application/json