"""empty message

Revision ID: 65a5d444be42
Revises: 6fd1243075e7
Create Date: 2022-05-23 11:39:42.382473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a5d444be42'
down_revision = '6fd1243075e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario_padre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario_padre',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comentaroId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comentaroId'], ['comentario.id'], name='comentario_padre_comentaroId_fkey'),
    sa.PrimaryKeyConstraint('id', name='comentario_padre_pkey')
    )
    # ### end Alembic commands ###
