"""empty message

Revision ID: 6cd6affd94a5
Revises: d5add48e96b6
Create Date: 2022-07-09 19:30:49.607965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd6affd94a5'
down_revision = 'd5add48e96b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('rol', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'rol')
    # ### end Alembic commands ###
