"""empty message

Revision ID: d5add48e96b6
Revises: 65a5d444be42
Create Date: 2022-05-25 15:31:13.960790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5add48e96b6'
down_revision = '65a5d444be42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comentarioPadre', sa.Column('comentarioId', sa.Integer(), nullable=True))
    op.drop_constraint('comentarioPadre_comentaroId_fkey', 'comentarioPadre', type_='foreignkey')
    op.create_foreign_key(None, 'comentarioPadre', 'comentario', ['comentarioId'], ['id'])
    op.drop_column('comentarioPadre', 'comentaroId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comentarioPadre', sa.Column('comentaroId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comentarioPadre', type_='foreignkey')
    op.create_foreign_key('comentarioPadre_comentaroId_fkey', 'comentarioPadre', 'comentario', ['comentaroId'], ['id'])
    op.drop_column('comentarioPadre', 'comentarioId')
    # ### end Alembic commands ###
